# Generated by Django 4.0.2 on 2022-02-16 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchman',
            name='email',
        ),
    ]
