# Generated by Django 4.0.2 on 2022-02-17 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchman',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Chairmen',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Watchman',
        ),
    ]
