# Generated by Django 4.0.2 on 2022-02-18 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chairmen',
            name='address',
        ),
    ]
