# Generated by Django 4.0.2 on 2022-02-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_chairmen_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chairmen',
            name='pincode',
        ),
        migrations.AddField(
            model_name='chairmen',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chairmen',
            name='job_address',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chairmen',
            name='job_profession',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chairmen',
            name='vehical_details',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chairmen',
            name='vehical_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
