# Generated by Django 4.0.2 on 2022-02-18 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_chairmen_pincode_chairmen_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chairmen',
            name='address',
        ),
    ]
