# Generated by Django 4.0.2 on 2022-02-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_member'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chairmen',
            new_name='Chairman',
        ),
    ]
