# Generated by Django 4.0.2 on 2022-02-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_user_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairman',
            name='pic',
            field=models.FileField(default='myapp/images/socity.jpg', upload_to='myapp/images/'),
        ),
        migrations.AddField(
            model_name='member',
            name='pic',
            field=models.FileField(default='myapp/images/socity.jpg', upload_to='myapp/images/'),
        ),
        migrations.AddField(
            model_name='watchman',
            name='pic',
            field=models.FileField(default='myapp/images/socity.jpg', upload_to='myapp/images/'),
        ),
    ]
