# Generated by Django 4.0.2 on 2022-03-12 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_chairman_pic_member_pic_watchman_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='watchman',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Chairman',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Watchman',
        ),
    ]
