# Generated by Django 4.0.2 on 2022-03-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairman',
            name='pic',
            field=models.FileField(default='media/images/socity.jpg', upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='pic',
            field=models.FileField(default='media/images/socity.jpg', upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.FileField(default='media/images/socity.jpg', upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='watchman',
            name='pic',
            field=models.FileField(default='media/images/socity.jpg', upload_to='media/images/'),
        ),
    ]
