# Generated by Django 4.0.2 on 2022-04-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_chairman_pic_alter_member_pic_alter_user_pic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=30)),
                ('dob', models.DateField(auto_now_add=True)),
                ('event_dis', models.CharField(max_length=30)),
                ('pic', models.FileField(default='media/images/socity.jpg', upload_to='media/images/')),
            ],
        ),
    ]
