# Generated by Django 4.0.2 on 2022-04-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_chairman_pic_alter_event_pic_alter_member_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairman',
            name='pic',
            field=models.FileField(default='media/images/society.jpg', upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pic',
            field=models.FileField(default='media/socity.jpg', upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='pic',
            field=models.FileField(default='media/society.jpg', upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.FileField(default='media/society.jpg', upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='watchman',
            name='pic',
            field=models.FileField(default='media/socity.jpg', upload_to='media/images/'),
        ),
    ]
