# Generated by Django 4.0.4 on 2022-04-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_title', models.CharField(max_length=20)),
                ('suggestion_dis', models.CharField(max_length=50)),
            ],
        ),
    ]
