# Generated by Django 4.0.4 on 2022-04-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(default='media/', upload_to='media/video/')),
                ('dob', models.DateField(auto_now_add=True)),
                ('video_name', models.CharField(max_length=30)),
            ],
        ),
    ]
