# Generated by Django 4.0.4 on 2022-04-29 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chairman',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Complain',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.RemoveField(
            model_name='member',
            name='c_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.DeleteModel(
            name='photos',
        ),
        migrations.DeleteModel(
            name='Suggestion',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='Visitors',
        ),
        migrations.RemoveField(
            model_name='watchman',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Chairman',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Watchman',
        ),
    ]
