# Generated by Django 4.0.4 on 2022-04-29 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0034_remove_chairman_user_id_delete_complain_delete_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_no', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=15, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=10, null=True)),
                ('job_profession', models.CharField(max_length=20, null=True)),
                ('job_address', models.CharField(max_length=20, null=True)),
                ('vehical_type', models.CharField(max_length=20, null=True)),
                ('vehical_details', models.CharField(max_length=20, null=True)),
                ('pic', models.FileField(default='media/images/society.jpg', upload_to='media/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_title', models.CharField(max_length=20)),
                ('com_dis', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=30)),
                ('dob', models.DateField(auto_now_add=True)),
                ('event_dis', models.CharField(max_length=30)),
                ('pic', models.FileField(default='media/socity.jpg', upload_to='media/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=20)),
                ('dob', models.DateField(auto_now_add=True)),
                ('notice_dis', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(default='media/socity.jpg', upload_to='media/images/')),
                ('dob', models.DateField(auto_now_add=True)),
                ('photo_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_title', models.CharField(max_length=20)),
                ('suggestion_dis', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('otp', models.IntegerField(default=459)),
                ('pic', models.FileField(default='media/society.jpg', upload_to='media/images/')),
                ('role', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(default='media/', upload_to='media/video/')),
                ('dob', models.DateField(auto_now_add=True)),
                ('video_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('flat_no', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('contact', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watchman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=15, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=10, null=True)),
                ('pic', models.FileField(default='media/socity.jpg', upload_to='media/images/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_no', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=15, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=10, null=True)),
                ('job_profession', models.CharField(max_length=20, null=True)),
                ('job_address', models.CharField(max_length=20, null=True)),
                ('vehical_type', models.CharField(max_length=20, null=True)),
                ('vehical_details', models.CharField(max_length=20, null=True)),
                ('pic', models.FileField(default='media/society.jpg', upload_to='media/images/')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.chairman')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='chairman',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
