# Generated by Django 4.0.4 on 2022-04-29 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
