# Generated by Django 4.0.4 on 2022-05-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_suggestion_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchman',
            name='email',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
